# Generated by Django 5.2.4 on 2025-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('afiliacao', models.CharField(blank=True, max_length=255)),
                ('aliados', models.TextField(blank=True)),
                ('inimigos', models.TextField(blank=True)),
            ],
        ),
    ]
